# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: yuque to readme
      uses: RaoHai/yuque2Readme@1.0.2
      with:
        # secrets.YUQUE_TOKEN. 语雀的 token，去 https://www.yuque.com/settings/tokens 里找。需要读取你的知识库和文档。
        yuque-token: ${{secrets.YUQUE}}
        # 填你自己的空间标识。比如语雀的博客是： `yuque/blog`
        yuque-namespace: chenzesam/cd5hio
        # 是否只列出已发布的文章
        yuque-doc-public-only: true
        # Which file to write
        yuque-output-file: README.md
        # Template for generate output
        yuque-template-file: README.template.md
        yuque-doc-limit: 5

#     - name: Result
#       run: |-
#         cat README.skylark.md

    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "chenzesam@gmail.com"
        git config --global user.name "chenzesam"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
